# Generated by Django 5.1.3 on 2024-12-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TASchedulerApp', '0002_labsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='home_address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='myuser',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
        ),
    ]
