# Generated by Django 5.1.2 on 2024-12-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TASchedulerApp', '0004_myuser_office_hours_myuser_office_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
