# Generated by Django 5.1.2 on 2024-12-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TASchedulerApp', '0005_myuser_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='skills',
            field=models.TextField(default=''),
        ),
    ]
